services:
  backend:
    image: backend
    ports:
      - "80:80"
    entrypoint: "sh docker-entrypoint/django-entrypoint.sh"
    env_file:
      - ../dotenv/.env.dev
    volumes:
      - ~/features/dotenv:/dotenv
      - ~/features/logs:/logs
    restart: unless-stopped
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 1m
      test: curl -f http://localhost/api/health_check/ || exit 1
    environment:
      - DJANGO_SETTINGS_MODULE=ainsight_backend.config.settings.production

  celery_flower:
    image: backend
    ports:
      - "5555:5555"
    depends_on:
      backend:
        condition: service_healthy
    entrypoint: "sh docker-entrypoint/flower-entrypoint.sh"
    env_file:
      - ../dotenv/.env.dev
    volumes:
      - ~/features/dotenv:/dotenv
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
