services:
  backend:
    image: ainsight-prod-ecr
    ports:
      - "80:80"
    entrypoint: "sh docker-entrypoint/django-entrypoint.sh"
    env_file:
      - ./dotenv/.env.prod
    volumes:
      - ~/features/dotenv:/dotenv
      - ~/features/logs:/logs
    restart: unless-stopped
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 1m
      test: curl -f http://localhost/api/health_check/ || exit 1
    environment:
      - DJANGO_SETTINGS_MODULE=ainsight_backend.config.settings.production
